### ISSUE TITLE
Remove specimenTools and easyZoom?

### ISSUE THREAD

**Issue by davelab6** [googlefonts/ebgaramond-specimen#10]
Cybage found the [third_party](https://github.com/googlefonts/ebgaramond-specimen/tree/main/src/third_party) specimenTools and easyZoom folders present in the codebase, but they seem not to be linked or used anywhere - can they be deleted?

**Comment by Ashler** [comment]
Both third_party files are used in the page. 

easyZoom is the one in charge of the "Past & Present" zooming functionality (available when clicking on New Version/Old Version buttons).
And specimenTools the one for creating the Styles and Features controls on the "Try EB Garamond" section. This allows users to test the options of the font (change text, otfs and styles).

**Comment by davelab6** [comment]
Thanks for confirming
