### ISSUE TITLE
"Site not found" at https://ashler.github.io/ebg-website

### ISSUE THREAD

**Issue by arrowtype** [googlefonts/ebgaramond-specimen#5]
The link to the site from the README here and from the Ashler website is currently broken ([https://ashler.github.io/ebg-website](https://ashler.github.io/ebg-website)).

It should be [https://googlefonts.github.io/ebgaramond-specimen/](https://googlefonts.github.io/ebgaramond-specimen/)

**Comment by davelab6** [comment]
Fixed in https://github.com/googlefonts/ebgaramond-specimen/commit/973339259e0123f687eb688b93808420baff9f6f
