### ISSUE TITLE
Add build script and update README

### ISSUE THREAD

**Issue by davelab6** [googlefonts/ebgaramond-specimen#8]
Google web development vendor Cybage asks,

> Code base([GitHub.com/GoogleFonts/Ebgaramond-specimen )](http://github.com/GoogleFonts/Ebgaramond-specimen) provided for [Eb Garamond-specimen site](https://googlefonts.github.io/ebgaramond-specimen/) doesn't have a start script or webpack to run it locally. Also, we've checked the readme file but it is not updated with instructions. Please let us know if there's anything which we're missing to start the server locally.

**Comment by davelab6** [comment]
The build command is `gulp` as there is a gulpfile.js in the root

**Comment by Ashler** [comment]
Readme file update! :)
