### ISSUE TITLE
Languages List page?

### ISSUE THREAD

**Issue by davelab6** [googlefonts/ebgaramond-specimen#9]
Cybage observed there's one more page https://googlefonts.github.io/ebgaramond-specimen/languages-list present in the codebase. How should this be used?

**Comment by Ashler** [comment]
language-list.html page it's used as a way to load data from an external file for initial smaller DOM in the single page. It can be for sure changed to a json file, with the same purpose.

We can discuss further if you need the JS involve to changing/deleting it.

**Comment by davelab6** [comment]
Thanks for explaining
